### ISSUE TITLE
@timestamp as datetime iso-formatted string

### ISSUE THREAD

**Issue by casabre** [Rohde-Schwarz/pytest-fluent#39]
Currently, the timestamp is forwarded as Linux time integer. Could we have another CLI parameter in order to activate conversion to an iso-formatted string?

**Comment by lambiase** [comment]
I cannot reproduce this behavior with `--fluentd-timestamp` (the timestamp is ISO-formatted):

```
pytest tests --fluentd-timestamp "@timestamp"
```

```
...
2023-06-23 08:05:56 +0000 test.pytest: {
  "status": "finish",
  "duration": 0.14519786834716797,
  "stage": "session",
  "sessionId": "541e35f2-2356-4d94-8ce5-db542a5951f8",
  "@timestamp": "2023-06-23T08:05:56.960606",
  "tag": "test",
  "label": "pytest"
}
```

**Comment by casabre** [comment]
I guess I know why... I have used "date" for `--fluentd-timestamp "date"` and probably, the `emit_with_timestamp` overrode it 🤔.

Maybe we should patch the `emit` function? Anyway having an unwanted timestamp is unintentional data.

**Comment by lambiase** [comment]
Ok, I think I understand the issue.

A fluentd event has 3 components:

- `tag`
- `time`
- `record`

The format of the `time` component cannot be freely changed (it is described in the Fluentd msgpack protocol specification):
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#eventtime-ext-format

`--fluentd-timestamp` defines the key of an _additional_ timestamp in ISO format that can be added to the `record` component.

I think we have these options:

- keep things as they are, i.e. the additional timestamp optionally added to the record by `--fluentd-timestamp` (to be consistent with the timestamp in `--fluentd-timestamp` we should probably set `nanosecond_precision=True` in the `FluentSender`)
- drop `--fluentd-timestamp` entirely

**Comment by casabre** [comment]
Seems that it was working properly
