### ISSUE TITLE
Allow pytest-fluent configuration via ini file

### ISSUE THREAD

**Issue by lambiase** [Rohde-Schwarz/pytest-fluent#4]
It would be nice to be able to set `pytest-fluent` options (e.g. `fluentd-host`, `fluentd-port`, etc.) in the `pytest.ini` or `pyproject.toml` files without specifying them every time in the CLI.

If the same option is specified in both CLI and ini file, the CLI option would have higher priority and override the second.

**Comment by casabre** [comment]
For the moment, we should consider also `tox` configuration files.
